baseurl         = "https://juanavalos.netlify.com/"
theme           = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = "juanavalos"
paginate        = 6
title           = "Juan Avalos"
#SectionPagesMenu = "main"

[params]
  title       = "Juan Avalos"
  subtitle    = "Writer | Engineer | Coffee Enthusiast"

  cover       = "uploads/coverphoto.jpg"
  description = "Professional Portfolio and Creative Outlet"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "MrJuantastico"
  igName = "mr_juantastico"
  githubName = "MrJuantastic"

  logo = ""
  orgName = "Juan Avalos"
  orgWebsite = "https://juanavalos.netlify.com"
  orgDescription = ""

  author = "Juan Avalos"
  authorAvatar = "uploads/juan.png"
  authorLocation = "Austin, TX"
  authorWebsite = "https://juanavalos.netlify.com"
  authorDescription = "I am engineer and aspiring writer with a passion to tell stories that foster hope, inspiration, and empowerment for current and future generations. Besides that I am a coffee enthusiast, a dad joke aficionado, a fantasy football fanatic and a dog lover. "

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
    post = "/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 200

[[menu.main]]
    name = "Portfolio"
    url = "/categories"
    weight = 198