baseurl         = "/"
theme           = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Juan Avalos"
  subtitle    = "Writer | Engineer | Coffee Enthusiast"

  cover       = "uploads/juan_fish_slp_2.jpg"
  description = "Professional Portfolio and Creative Outlet"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "MrJuantastic"
  igName = "mr_juantastic"
  githubName = "MrJuantastic"

  logo = ""
  orgName = "Juan Avalos"
  orgWebsite = "https://juanavalos.netlify.com"
  orgDescription = ""

  author = "Juan Avalos"
  authorAvatar = "uploads/juan.png"
  authorLocation = "Austin, TX"
  authorWebsite = "https://juanavalos.netlify.com"
  authorDescription = "TBD"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
    post = "/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 200

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 198